const title = document.querySelector("header");
const body = document.querySelector("body");
const count = document.querySelector("h4.count");
const main = document.querySelector("main.login");
const inputId = document.querySelector(".signID");
const inputPW = document.querySelector(".signPassward");
const submitButton = document.querySelector(".submit");
const signForm = document.querySelector(".signup-form")
const loginForm = document.querySelector(".login-form")
const loginButton = document.querySelector(".login-form button")
const loginID = document.querySelector(".login-form .loginId")
const loginPW = document.querySelector(".login-form .loginPW")
